DEBUG = True
SECRET_KEY = 'UUC5324K4D2PNQR0CGF3'
SQLALCHEMY_DATABASE_URI = 'sqlite:////Users/fcarrizalest/Sites/pySt/foo.db'

SQLALCHEMY_BINDS = {
    'cv':        'sqlite:////Users/fcarrizalest/Sites/pySt/cv.db'
}

SECURITY_POST_LOGIN_VIEW = '/'
SECURITY_PASSWORD_HASH = 'YIX0N2GDH7M1AA85V9TT'
SECURITY_PASSWORD_SALT = '8OS94MDLPG0732DXWYW0'
SECURITY_REMEMBER_SALT = '68QIXVBSDKX528ZLEH0A'
SECURITY_RESET_SALT = 'UH942QNAZ1HJ5TPTV4OA'
SECURITY_RESET_WITHIN = '5 days'
SECURITY_CONFIRM_WITHIN = '5 days'
RECAPTCHA_PARAMETERS = { 'render': 'explicit'}
RECAPTCHA_DATA_ATTRS = {'theme': 'dark'}
RECAPTCHA_PUBLIC_KEY = "6LfyEw4TAAAAAEf7aOIbBPbdf23IRdhfCFfJXeQJ"